# Generated by Django 3.2.25 on 2024-07-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0108_jobbutton_enabled'),
        ('containerlab', '0003_alter_topology_dynamic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='git_repository',
            field=models.ForeignKey(blank=True, limit_choices_to={'provided_contents__contains': 'containerlab.topology'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containerlab_topologies', to='extras.gitrepository'),
        ),
    ]
