# Generated by Django 3.2.25 on 2024-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerlab', '0004_topology_git_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='topology_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
